// GENERATED by docs/verification/core/gen_weather_cases.py from
// services/nycsim_live/{metar,weather}.py over the fixtures in core/tests/data/weather/.
// DO NOT EDIT BY HAND.
#pragma once

#include <cstdint>
#include <limits>

namespace nycsim_test_weather {

inline constexpr double kNaN = std::numeric_limits<double>::quiet_NaN();

struct ExpectedState {
  const char* station;
  int32_t source;
  double observed_at;
  double temp_c, dewpoint_c, rh;
  double wind_mps, wind_gust_mps, wind_dir_deg;
  double wind_from_heading, wind_to_heading;
  int32_t precip_type;
  double precip_rate_mmph;
  int32_t precip_rate_basis;
  double cloud_cover, visibility_m, pressure_hpa;
  double snow_depth_cm;
  int32_t snow_depth_source;
  double snowfall_rate_cmph;
  bool thunder;
  uint16_t obscuration;
  double now_unix;
};

struct MetarCase {
  const char* label;
  const char* text;
  double reference_unix;
  double observation_unix;
  const char* station;
  bool nil;
  bool automatic;
  double wind_dir, wind_speed, wind_gust;
  bool wind_variable, wind_calm;
  double visibility_m;
  bool vis_less, vis_greater, cavok;
  int32_t n_weather_groups, n_clouds, n_rvr, n_unparsed;
  double temp_c, dewpoint_c, altimeter_hpa, slp_hpa;
  double precip_1h_mm, snow_depth_cm, snowfall_6h_cm, snow_we_mm;
  double peak_wind_dir, peak_wind_mps;
  double ceiling_m, cloud_cover;
  int32_t precip_type;
  double precip_rate;
  int32_t precip_basis;
  bool thunder;
  uint16_t obscuration;
  const char* trend;
};
inline constexpr MetarCase kMetarCases[] = {
    {"calm_clear_knyc", "KNYC 061051Z 00000KT 10SM CLR 18/16 A2996 RMK AO2 SLP138 T01780156", 1788692400.0,
     1788691860.0,
     "KNYC", false, false,
     kNaN, 0.0, kNaN, false, true,
     16093.4, false, true, false,
     0, 0, 0, 0,
     17.8, 15.6, 1014.6, 1013.8,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     kNaN, 0.0,
     0, 0.0, 0,
     false, 0,
     ""},
    {"light_rain_bkn", "KLGA 141251Z 09012KT 4SM -RA BR BKN008 OVC015 12/11 A2985 RMK AO2 P0004 SLP108 T01220111", 1773493200.0,
     1773492660.0,
     "KLGA", false, false,
     90.0, 6.173, kNaN, false, false,
     6437.4, false, false, false,
     2, 2, 0, 0,
     12.2, 11.1, 1010.8, 1010.8,
     1.016, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     243.8, 1.0,
     1, 1.016, 1,
     false, 1,
     ""},
    {"heavy_thunderstorm", "KJFK 231954Z 24018G31KT 1 1/2SM +TSRA BR SCT012 BKN025CB OVC040 22/21 A2971 RMK AO2 TSB48 P0035 SLP055 T02220211", 1784836800.0,
     1784836440.0,
     "KJFK", false, false,
     240.0, 9.26, 15.948, false, false,
     2414.0, false, false, false,
     2, 3, 0, 0,
     22.2, 21.1, 1006.1, 1005.5,
     8.89, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     762.0, 1.0,
     1, 8.89, 1,
     true, 1,
     ""},
    {"moderate_snow", "KNYC 070851Z 03014G22KT 1/2SM SN FZFG VV006 M03/M05 A2978 RMK AO2 SNINCR 2/6 4/008 P0006 SLP086 T10281050", 1767776400.0,
     1767775860.0,
     "KNYC", false, false,
     30.0, 7.202, 11.318, false, false,
     804.7, false, false, false,
     2, 1, 0, 0,
     -2.8, -5.0, 1008.5, 1008.6,
     1.524, 20.32, kNaN, kNaN,
     kNaN, kNaN,
     182.9, 1.0,
     2, 1.524, 1,
     false, 2,
     ""},
    {"freezing_rain", "KEWR 160951Z 05009KT 2SM -FZRA BR OVC006 M01/M02 A2996 RMK AO2 P0002 SLP146 T10061017", 1768557600.0,
     1768557060.0,
     "KEWR", false, false,
     50.0, 4.63, kNaN, false, false,
     3218.7, false, false, false,
     2, 1, 0, 0,
     -0.6, -1.7, 1014.6, 1014.6,
     0.508, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     182.9, 1.0,
     4, 0.508, 1,
     false, 1,
     ""},
    {"ice_pellets_mix", "KLGA 041151Z 36011KT 3/4SM -PLSN OVC009 M01/M02 A3005 RMK AO2 P0003 SLP178 T10061017", 1770206400.0,
     1770205860.0,
     "KLGA", false, false,
     360.0, 5.659, kNaN, false, false,
     1207.0, false, false, false,
     1, 1, 0, 0,
     -0.6, -1.7, 1017.6, 1017.8,
     0.762, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     274.3, 1.0,
     3, 0.762, 1,
     false, 0,
     ""},
    {"drizzle_fog", "KJFK 120651Z VRB03KT 1/4SM DZ FG VV002 09/09 A3011 RMK AO2 SLP196 T00890089", 1775977200.0,
     1775976660.0,
     "KJFK", false, false,
     kNaN, 1.543, kNaN, true, false,
     402.3, false, false, false,
     2, 1, 0, 0,
     8.9, 8.9, 1019.6, 1019.6,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     61.0, 1.0,
     5, 0.5, 2,
     false, 2,
     ""},
    {"vicinity_thunder", "KNYC 251851Z 20008KT 10SM VCTS SCT045CB BKN090 27/19 A2989 RMK AO2 TCU ALQDS SLP120 T02720189", 1782414000.0,
     1782413460.0,
     "KNYC", false, false,
     200.0, 4.116, kNaN, false, false,
     16093.4, false, true, false,
     1, 2, 0, 0,
     27.2, 18.9, 1012.2, 1012.0,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     2743.2, 0.75,
     0, 0.0, 0,
     true, 0,
     ""},
    {"cavok_metres", "EGLL 011220Z 24008MPS CAVOK 15/07 Q1021 NOSIG", 1777640400.0,
     1777638000.0,
     "EGLL", false, false,
     240.0, 8.0, kNaN, false, false,
     16093.44, false, true, true,
     0, 0, 0, 0,
     15.0, 7.0, 1021.0, kNaN,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     kNaN, 0.0,
     0, 0.0, 0,
     false, 0,
     "NOSIG"},
    {"metres_visibility", "LFPG 011230Z 27010KT 8000 -SHRA FEW012 SCT020 BKN035 14/11 Q1013 TEMPO 4000 SHRA", 1777640400.0,
     1777638600.0,
     "LFPG", false, false,
     270.0, 5.144, kNaN, false, false,
     8000.0, false, false, false,
     1, 3, 0, 0,
     14.0, 11.0, 1013.0, kNaN,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     1066.8, 0.75,
     1, 1.0, 2,
     false, 0,
     "TEMPO 4000 SHRA"},
    {"rvr_and_variable", "KJFK 010851Z 31015G25KT 280V350 1/2SM R04R/2000FT FG VV002 05/05 A2970 RMK AO2 PK WND 32032/0812 SLP051 T00500050", 1793523600.0,
     1793523060.0,
     "KJFK", false, false,
     310.0, 7.717, 12.861, false, false,
     804.7, false, false, false,
     1, 1, 1, 0,
     5.0, 5.0, 1005.8, 1005.1,
     kNaN, kNaN, kNaN, kNaN,
     320.0, 16.462,
     61.0, 1.0,
     0, 0.0, 0,
     false, 2,
     ""},
    {"mixed_fraction_vis", "KEWR 020551Z 08006KT 1 3/4SM BR OVC004 07/07 A3021 RMK AO2 SLP231 T00720072", 1790920800.0,
     1790920260.0,
     "KEWR", false, false,
     80.0, 3.087, kNaN, false, false,
     2816.4, false, false, false,
     1, 1, 0, 0,
     7.2, 7.2, 1023.0, 1023.1,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     121.9, 1.0,
     0, 0.0, 0,
     false, 1,
     ""},
    {"missing_dewpoint", "KTEB 031451Z AUTO 25009KT 10SM SCT200 24/ A2999 RMK AO2", 1785769200.0,
     1785768660.0,
     "KTEB", false, true,
     250.0, 4.63, kNaN, false, false,
     16093.4, false, true, false,
     0, 1, 0, 0,
     24.0, kNaN, 1015.6, kNaN,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     kNaN, 0.4375,
     0, 0.0, 0,
     false, 0,
     ""},
    {"haze_smoke", "KLGA 121751Z 22006KT 5SM HZ FU SKC 31/17 A2988 RMK AO2 SLP116 T03110172", 1781287200.0,
     1781286660.0,
     "KLGA", false, false,
     220.0, 3.087, kNaN, false, false,
     8046.7, false, false, false,
     2, 0, 0, 0,
     31.1, 17.2, 1011.9, 1011.6,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     kNaN, 0.0,
     0, 0.0, 0,
     false, 68,
     ""},
    {"blowing_snow_heavy", "KJFK 291251Z 01025G38KT 1/4SM +SN BLSN VV003 M07/M10 A2951 RMK AO2 4/012 931025 933015 P0008 SLP998 T10721100", 1769691600.0,
     1769691060.0,
     "KJFK", false, false,
     10.0, 12.861, 19.549, false, false,
     402.3, false, false, false,
     2, 1, 0, 0,
     -7.2, -10.0, 999.3, 999.8,
     2.032, 30.48, 6.35, 38.1,
     kNaN, kNaN,
     91.4, 1.0,
     2, 2.032, 1,
     false, 0,
     ""},
    {"hail_shower", "KEWR 152051Z 27020G35KT 2SM +TSRAGR SCT020 BKN035CB 24/19 A2980 RMK AO2 GR 1/2 P0045 SLP090 T02440189", 1778878800.0,
     1778878260.0,
     "KEWR", false, false,
     270.0, 10.289, 18.006, false, false,
     3218.7, false, false, false,
     1, 2, 0, 0,
     24.4, 18.9, 1009.1, 1009.0,
     11.43, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     1066.8, 0.75,
     3, 11.43, 1,
     true, 0,
     ""},
    {"clear_q_pressure", "EDDF 011250Z 07004KT 9999 FEW035 21/09 Q1018 NOSIG", 1780318800.0,
     1780318200.0,
     "EDDF", false, false,
     70.0, 2.058, kNaN, false, false,
     16093.44, false, true, false,
     0, 1, 0, 0,
     21.0, 9.0, 1018.0, kNaN,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     kNaN, 0.1875,
     0, 0.0, 0,
     false, 0,
     "NOSIG"},
    {"nil_report", "KXYZ 011200Z NIL", 1780318800.0,
     1780315200.0,
     "KXYZ", true, false,
     kNaN, kNaN, kNaN, false, false,
     kNaN, false, false, false,
     0, 0, 0, 0,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     kNaN, kNaN,
     0, 0.0, 0,
     false, 0,
     ""},
    {"wind_missing_slash", "KJFK 011200Z /////KT 10SM CLR 20/10 A3000", 1780318800.0,
     1780315200.0,
     "KJFK", false, false,
     kNaN, kNaN, kNaN, false, false,
     16093.4, false, true, false,
     0, 0, 0, 0,
     20.0, 10.0, 1015.9, kNaN,
     kNaN, kNaN, kNaN, kNaN,
     kNaN, kNaN,
     kNaN, 0.0,
     0, 0.0, 0,
     false, 0,
     ""},
    {"snow_grains_low_vis", "KNYC 050751Z 02008KT 0000 SG VV001 M05/M07 A3008 RMK AO2 4/003", 1770278400.0,
     1770277860.0,
     "KNYC", false, false,
     20.0, 4.116, kNaN, false, false,
     50.0, true, false, false,
     1, 1, 0, 0,
     -5.0, -7.0, 1018.6, kNaN,
     kNaN, 7.62, kNaN, kNaN,
     kNaN, kNaN,
     30.5, 1.0,
     2, 1.5, 2,
     false, 0,
     ""},
};
inline constexpr int kMetarCaseCount = 20;

inline constexpr ExpectedState kNwsKNYC = {
    "KNYC", 0, 1788691860.0,
    17.8, 15.6, 86.962935510424,
    0.0, kNaN, kNaN,
    kNaN, kNaN,
    0, 0.0, 0,
    0.0, 16090.0, 1013.8,
    kNaN, 0, kNaN,
    false, 0, 1788692160.0,
};
inline constexpr bool kNwsKNYCBlendApplied = true;
inline constexpr ExpectedState kNwsKNYCBlended = {
    "KNYC", 0, 1788691860.0,
    17.244444444444447, 15.6, 90.06520717592392,
    0.0, kNaN, kNaN,
    kNaN, kNaN,
    0, 0.0, 0,
    0.040000000000000036, 16090.0, 1013.8,
    kNaN, 0, kNaN,
    false, 0, 1788694860.0,
};
inline constexpr ExpectedState kNwsKLGA = {
    "KLGA", 0, 1788693600.0,
    19.0, 14.0, 72.761266404652,
    2.5700000000000003, kNaN, 40.0,
    50.0, 230.0,
    0, 0.0, 0,
    0.0, 16093.44, 1013.8847999999999,
    kNaN, 0, kNaN,
    false, 0, 1788693900.0,
};
inline constexpr bool kNwsKLGABlendApplied = true;
inline constexpr ExpectedState kNwsKLGABlended = {
    "KLGA", 0, 1788693600.0,
    20.11111111111111, 14.0, 67.90849366419229,
    2.5700000000000003, kNaN, 40.0,
    50.0, 230.0,
    0, 0.0, 0,
    0.0, 16093.44, 1013.8847999999999,
    kNaN, 0, kNaN,
    false, 0, 1788696600.0,
};
inline constexpr ExpectedState kNwsKJFK = {
    "KJFK", 0, 1788693900.0,
    18.0, 16.0, 88.10014352739,
    0.0, kNaN, kNaN,
    kNaN, kNaN,
    0, 0.0, 0,
    0.0, 16093.44, 1014.2234,
    kNaN, 0, kNaN,
    false, 0, 1788694200.0,
};
inline constexpr bool kNwsKJFKBlendApplied = true;
inline constexpr ExpectedState kNwsKJFKBlended = {
    "KJFK", 0, 1788693900.0,
    19.11111111111111, 16.0, 82.18089095196623,
    0.0, kNaN, kNaN,
    kNaN, kNaN,
    0, 0.0, 0,
    0.0, 16093.44, 1014.2234,
    kNaN, 0, kNaN,
    false, 0, 1788696900.0,
};
inline constexpr ExpectedState kOpenMeteo = {
    "open-meteo:40.78858,-73.9661", 1, 1788694200.0,
    18.8, 16.0, 84.0,
    1.53, 2.7, 58.0,
    32.0, 212.0,
    0, 0.0, 0,
    0.91, 16700.0, 1014.3,
    kNaN, 0, kNaN,
    false, 0, 1788694320.0,
};
inline constexpr ExpectedState kMetarKNYC = {
    "KNYC", 2, 1788691860.0,
    17.8, 15.6, 86.96293551042443,
    0.0, kNaN, kNaN,
    kNaN, kNaN,
    0, 0.0, 0,
    0.0, 16093.4, 1013.8,
    kNaN, 0, kNaN,
    false, 0, 1788692460.0,
};
inline constexpr ExpectedState kMetarKLGA = {
    "KLGA", 2, 1788691860.0,
    18.9, 13.9, 72.7434273158572,
    2.572, kNaN, 340.0,
    110.0, 290.0,
    0, 0.0, 0,
    0.4375, 16093.4, 1013.6,
    kNaN, 0, kNaN,
    false, 0, 1788692460.0,
};
inline constexpr ExpectedState kMetarKJFK = {
    "KJFK", 2, 1788692820.0,
    17.8, 15.0, 83.67764288750747,
    2.058, kNaN, 30.0,
    60.0, 240.0,
    0, 0.0, 0,
    0.75, 16093.4, 1013.9,
    kNaN, 0, kNaN,
    false, 0, 1788693420.0,
};
inline constexpr ExpectedState kMetarKEWR = {
    "KEWR", 2, 1788691860.0,
    18.3, 16.1, 87.00958282281972,
    4.116, kNaN, 80.0,
    10.0, 190.0,
    0, 0.0, 0,
    0.4375, 16093.4, 1013.7,
    kNaN, 0, kNaN,
    false, 0, 1788692460.0,
};

}  // namespace nycsim_test_weather
