#pragma once
// GENERATED by unreal/tools/gen_ped_wardrobe.py from blender_out/character/npc_variety.json.
// Do not edit: run the generator.  tests/test_character.py fails if the two disagree.
//
// Which pedestrian body is dressed for which weather.  PedSim::assignAppearance already
// computes kPedCoat below 12 degrees and, before this table existed, drew the body
// uniformly over all archetypes and ignored it -- so the crowd wore July clothes in
// November (DEVIATIONS J53).
//
// Measured: which garments each body wears and which of them the wardrobe declares
// slot == "outerwear".  Chosen: that a hi-vis or delivery vest is a work layer and not
// warm clothing.  New York's real clothing distribution at a given temperature is measured
// nowhere in this project, so the split below is a rule, not an observation.

#include <cstdint>

namespace nycsim_gameplay
{
/// Bodies wearing a coat, a puffer or a jacket: archetypes 2, 5, 12, 15, 22.
inline constexpr uint32_t kPedWarmArchetypes = 0x00409024u;
/// Bodies in summer dress and no outer layer: archetypes 1, 11, 21.
inline constexpr uint32_t kPedSummerArchetypes = 0x00200802u;
/// Archetypes the table covers; a bit above this is not a body.
inline constexpr uint32_t kPedWardrobeArchetypes = 24u;

/// One of the archetypes in `mask`, drawn from `roll` (any 32-bit value); `fallback` when the mask is empty.
inline uint8_t pickArchetype(uint32_t mask, uint32_t roll, uint8_t fallback)
{
	if (mask == 0u)
	{
		return fallback;
	}
	uint32_t n = 0u;
	for (uint32_t m = mask; m != 0u; m &= m - 1u)
	{
		++n;
	}
	uint32_t want = roll % n;
	for (uint32_t i = 0u; i < 32u; ++i)
	{
		if ((mask & (1u << i)) == 0u)
		{
			continue;
		}
		if (want == 0u)
		{
			return static_cast<uint8_t>(i);
		}
		--want;
	}
	return fallback;
}
}  // namespace nycsim_gameplay
