"""Generate core/tests/astro/astro_cases.h from services/nycsim_live/astronomy.py.

Cross-check data for the C++ SPA/Moon port:
  * kSpaSamples    — Sun position (zenith, azimuth, RA, dec, distance) every 73 h through 2026 at
                     Central Park, plus the NREL reference site, computed by the Python reference;
  * kSunEventCases — sunrise / transit / sunset for NYC local dates spanning a year;
  * kMoonSamples   — Moon position, distance, illuminated fraction, phase angle and elongation;
  * kHengeCases    — Manhattanhenge full/half-sun dates and azimuths for 2024-2028.

Run: python3 docs/verification/core/gen_astro_cases.py > core/tests/astro/astro_cases.h
"""
from __future__ import annotations

import datetime as dt
import sys

sys.path.insert(0, "services")

from nycsim_live import astronomy as A, timesync as T  # noqa: E402

CP = A.CENTRAL_PARK


def r(x: float) -> str:
    return repr(float(x))


def main() -> int:
    print("// GENERATED by docs/verification/core/gen_astro_cases.py from")
    print("// services/nycsim_live/astronomy.py. DO NOT EDIT BY HAND.")
    print("#pragma once\n\n#include <cstdint>\n\nnamespace nycsim_test_astro {\n")

    print("struct SpaSample { double unix_s; double zenith, azimuth, ra, dec, r_au, e0, refraction; };")
    print("inline constexpr SpaSample kSpaSamples[] = {")
    t0 = dt.datetime(2026, 1, 1, 0, 17, 0, tzinfo=dt.timezone.utc)
    n = 0
    while n < 121:
        utc = t0 + dt.timedelta(hours=73 * n)
        p = A.solar_position(utc, CP)
        print(f"    {{{r(utc.timestamp())}, {r(p.zenith)}, {r(p.azimuth)}, {r(p.geocentric.alpha)}, "
              f"{r(p.geocentric.delta)}, {r(p.distance_au)}, {r(p.elevation_uncorrected)}, {r(p.refraction)}}},")
        n += 1
    print("};")
    print(f"inline constexpr int kSpaSampleCount = {n};\n")

    print("struct SunEventCase { int32_t y, mo, d; double sunrise, transit, sunset; };")
    print("inline constexpr SunEventCase kSunEventCases[] = {")
    dates = [dt.date(2026, 1, 1), dt.date(2026, 2, 14), dt.date(2026, 3, 8), dt.date(2026, 3, 20),
             dt.date(2026, 5, 28), dt.date(2026, 6, 21), dt.date(2026, 7, 12), dt.date(2026, 9, 22),
             dt.date(2026, 11, 1), dt.date(2026, 12, 21), dt.date(2024, 2, 29), dt.date(2030, 8, 3)]
    for d in dates:
        ev = A.sun_events_local(d, CP)
        print(f"    {{{d.year}, {d.month}, {d.day}, {r(ev.sunrise.timestamp())}, "
              f"{r(ev.transit.timestamp())}, {r(ev.sunset.timestamp())}}},")
    print("};")
    print(f"inline constexpr int kSunEventCaseCount = {len(dates)};\n")

    print("struct MoonSample { double unix_s; double azimuth, elevation, distance_km, k, phase_angle, "
          "elongation, ra, dec; int32_t phase_index; };")
    print("inline constexpr MoonSample kMoonSamples[] = {")
    t0 = dt.datetime(2026, 1, 3, 5, 41, 0, tzinfo=dt.timezone.utc)
    m = 0
    while m < 97:
        utc = t0 + dt.timedelta(hours=91 * m)
        p = A.moon_position(utc, CP)
        idx = A.PHASE_NAMES.index(p.phase_name)
        print(f"    {{{r(utc.timestamp())}, {r(p.azimuth)}, {r(p.elevation)}, {r(p.distance_km)}, "
              f"{r(p.illuminated_fraction)}, {r(p.phase_angle)}, {r(p.elongation)}, "
              f"{r(p.geocentric.right_ascension)}, {r(p.geocentric.declination)}, {idx}}},")
        m += 1
    print("};")
    print(f"inline constexpr int kMoonSampleCount = {m};\n")

    print("struct HengeCase { int32_t year; int32_t mo, d; int32_t full; double azimuth, delta; int32_t best; };")
    print("inline constexpr HengeCase kHengeCases[] = {")
    total = 0
    for year in (2024, 2025, 2026, 2027, 2028):
        for e in A.manhattanhenge(year, A.TUDOR_CITY_42ND):
            print(f"    {{{year}, {e.local_date.month}, {e.local_date.day}, {1 if e.kind == 'full' else 0}, "
                  f"{r(e.azimuth_deg)}, {r(e.delta_from_grid_deg)}, {1 if e.best_in_season else 0}}},")
            total += 1
    print("};")
    print(f"inline constexpr int kHengeCaseCount = {total};\n")
    print("}  // namespace nycsim_test_astro")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
