"""Fetch USNO rise/set/transit ground truth for Central Park and emit core/tests/astro/usno_cases.h.

Source: U.S. Naval Observatory Astronomical Applications API v4
(https://aa.usno.navy.mil/api/rstt/oneday) — U.S. Government work, public domain.
The raw responses are archived next to this script in usno_oneday.json.

Coordinates 40.7831 N, 73.9712 W (Central Park / KNYC). `tz` is the New York UTC offset in force on
that date, taken from services/nycsim_live/timesync.py so the returned local clock times are EST/EDT.

Run: python3 docs/verification/core/gen_usno_cases.py           # fetch + write both files
     python3 docs/verification/core/gen_usno_cases.py --offline  # regenerate the header from the archive
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib
import sys

sys.path.insert(0, "services")

import requests  # noqa: E402

from nycsim_live import timesync as T  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
ARCHIVE = HERE / "usno_oneday.json"
HEADER = pathlib.Path("core/tests/astro/usno_cases.h")
LAT, LON = 40.7831, -73.9712
DATES = [
    dt.date(2026, 1, 1), dt.date(2026, 2, 14), dt.date(2026, 3, 8), dt.date(2026, 3, 20),
    dt.date(2026, 4, 15), dt.date(2026, 5, 28), dt.date(2026, 6, 21), dt.date(2026, 7, 14),
    dt.date(2026, 9, 22), dt.date(2026, 11, 1), dt.date(2026, 11, 15), dt.date(2026, 12, 21),
    dt.date(2027, 3, 14), dt.date(2027, 8, 1), dt.date(2024, 2, 29),
]


def fetch() -> dict:
    out: dict[str, dict] = {}
    for d in DATES:
        noon = dt.datetime(d.year, d.month, d.day, 17, tzinfo=dt.timezone.utc)
        off, _ = T.nyc_offset(noon.timestamp())
        tz = off // 3600
        url = f"https://aa.usno.navy.mil/api/rstt/oneday?date={d.isoformat()}&coords={LAT},{LON}&tz={tz}"
        r = requests.get(url, timeout=60)
        r.raise_for_status()
        doc = r.json()
        doc["_tz_hours"] = tz
        out[d.isoformat()] = doc
        print(f"fetched {d} tz={tz}", file=sys.stderr)
    return out


def phen(doc: dict, group: str, name: str) -> str | None:
    for e in doc["properties"]["data"][group]:
        if e["phen"] == name:
            return e["time"]
    return None


def main() -> int:
    if "--offline" in sys.argv:
        archive = json.loads(ARCHIVE.read_text())
    else:
        archive = fetch()
        ARCHIVE.write_text(json.dumps(archive, indent=1, sort_keys=True))
    lines = []
    for iso, doc in sorted(archive.items()):
        y, mo, d = (int(x) for x in iso.split("-"))
        sr, st, ss = phen(doc, "sundata", "Rise"), phen(doc, "sundata", "Upper Transit"), phen(doc, "sundata", "Set")
        bct, ect = phen(doc, "sundata", "Begin Civil Twilight"), phen(doc, "sundata", "End Civil Twilight")
        frac = doc["properties"]["data"].get("fracillum") or "0%"
        if not (sr and st and ss and bct and ect):
            raise SystemExit(f"{iso}: incomplete USNO response")
        def mins(t: str) -> int:
            h, m = t.split(":")
            return int(h) * 60 + int(m)
        lines.append(
            f"    {{{y}, {mo}, {d}, {doc['_tz_hours']}, {mins(sr)}, {mins(st)}, {mins(ss)}, "
            f"{mins(bct)}, {mins(ect)}, {int(frac.rstrip('%'))}}},"
        )
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    with HEADER.open("w") as f:
        f.write("// GENERATED by docs/verification/core/gen_usno_cases.py.\n")
        f.write("// Ground truth: U.S. Naval Observatory Astronomical Applications API v4\n")
        f.write("// (https://aa.usno.navy.mil/api/rstt/oneday), a U.S. Government work in the public\n")
        f.write("// domain. Raw responses archived in docs/verification/core/usno_oneday.json.\n")
        f.write("// Site: 40.7831 N, 73.9712 W (Central Park / KNYC). Times are local minutes after\n")
        f.write("// midnight on the given EST/EDT offset (tz_hours). DO NOT EDIT BY HAND.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace nycsim_test_usno {\n\n")
        f.write("struct UsnoDay {\n  int32_t y, mo, d;\n  int32_t tz_hours;\n"
                "  int32_t rise_min, transit_min, set_min;\n"
                "  int32_t civil_begin_min, civil_end_min;\n  int32_t moon_fracillum_pct;\n};\n")
        f.write("inline constexpr UsnoDay kUsnoDays[] = {\n")
        f.write("\n".join(lines) + "\n")
        f.write("};\n")
        f.write(f"inline constexpr int kUsnoDayCount = {len(lines)};\n\n")
        f.write("}  // namespace nycsim_test_usno\n")
    print(f"wrote {HEADER} with {len(lines)} days", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
