"""Generate core/src/astro/SpaTables.inc from services/nycsim_live/astronomy.py.

The SPA (Reda & Andreas, NREL/TP-560-34302) Earth L/B/R series, the IAU 1980 nutation series and
Meeus' lunar tables 47.A/47.B are long numeric tables. They are emitted mechanically from the
Python reference so the C++ port cannot diverge by a transcription slip.

Run: python3 docs/verification/core/gen_spa_tables.py > core/src/astro/SpaTables.inc
"""
from __future__ import annotations

import sys

sys.path.insert(0, "services")

from nycsim_live import astronomy as A  # noqa: E402


def fmt(x: float) -> str:
    if isinstance(x, float) and x == int(x) and abs(x) < 1e15:
        return f"{int(x)}.0"
    return repr(x)


def main() -> int:
    print("// GENERATED by docs/verification/core/gen_spa_tables.py from")
    print("// services/nycsim_live/astronomy.py (Reda & Andreas, NREL/TP-560-34302 table A4.2;")
    print("// IAU 1980 nutation series; Meeus, Astronomical Algorithms 2nd ed. tables 47.A/47.B).")
    print("// Values are identical to the Python reference. DO NOT EDIT BY HAND.")
    print()
    for name, groups in (("kLTerms", A.L_TERMS), ("kBTerms", A.B_TERMS), ("kRTerms", A.R_TERMS)):
        counts = ", ".join(str(len(g)) for g in groups)
        total = sum(len(g) for g in groups)
        print(f"inline constexpr int {name}GroupCount = {len(groups)};")
        print(f"inline constexpr int {name}Counts[{len(groups)}] = {{{counts}}};")
        print(f"inline constexpr double {name}[{total}][3] = {{")
        for g in groups:
            for a, b, c in g:
                print(f"    {{{fmt(a)}, {fmt(b)}, {fmt(c)}}},")
        print("};")
        print()
    print(f"inline constexpr int kNutationCount = {len(A.NUTATION_Y)};")
    print(f"inline constexpr int8_t kNutationY[{len(A.NUTATION_Y)}][5] = {{")
    for row in A.NUTATION_Y:
        print("    {" + ", ".join(str(v) for v in row) + "},")
    print("};")
    print(f"inline constexpr double kNutationPE[{len(A.NUTATION_PE)}][4] = {{")
    for row in A.NUTATION_PE:
        print("    {" + ", ".join(fmt(float(v)) for v in row) + "},")
    print("};")
    print()
    print(f"inline constexpr int kMoonLrCount = {len(A.MOON_LR)};")
    print(f"inline constexpr int32_t kMoonLr[{len(A.MOON_LR)}][6] = {{")
    for row in A.MOON_LR:
        print("    {" + ", ".join(str(v) for v in row) + "},")
    print("};")
    print(f"inline constexpr int kMoonBCount = {len(A.MOON_B)};")
    print(f"inline constexpr int32_t kMoonB[{len(A.MOON_B)}][5] = {{")
    for row in A.MOON_B:
        print("    {" + ", ".join(str(v) for v in row) + "},")
    print("};")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
