"""Generate core/tests/time/dst_table.h from the IANA database via Python zoneinfo.

The table is the independent ground truth for the arithmetic US DST rule ported to
core/src/time/NyTime.cpp:

  * kDstTransitions — the exact POSIX instants of both America/New_York offset changes for every
    year 2007..2099 (93 x 2 values), found by an hour-resolution scan of the whole year;
  * kIsDstBits      — one bit per UTC day from 2007-01-01 to 2099-12-31 (33,968 days): set when
    12:00 UTC of that day is EDT. This is what "every day 2007-2099" means in the test;
  * kTransitionHours — for both transition days of every year, the offset at each of the 24 UTC
    hours, so the exact switch hour is checked as well.

Run: python3 docs/verification/core/gen_dst.py > core/tests/time/dst_table.h
"""
from __future__ import annotations

import datetime as dt
import sys
import zoneinfo

NY = zoneinfo.ZoneInfo("America/New_York")
Y0, Y1 = 2007, 2099


def offset_s(t: dt.datetime) -> int:
    return int(t.astimezone(NY).utcoffset().total_seconds())


def is_dst(t: dt.datetime) -> bool:
    d = t.astimezone(NY).dst()
    return bool(d and d.total_seconds() != 0)


def main() -> int:
    out = sys.stdout
    transitions: list[tuple[int, int, int]] = []
    for y in range(Y0, Y1 + 1):
        marks, prev = [], None
        t, end = dt.datetime(y, 1, 1, tzinfo=dt.timezone.utc), dt.datetime(y + 1, 1, 1, tzinfo=dt.timezone.utc)
        while t < end:
            o = offset_s(t)
            if prev is not None and o != prev:
                marks.append(int(t.timestamp()))
            prev = o
            t += dt.timedelta(hours=1)
        if len(marks) != 2:
            raise SystemExit(f"{y}: expected 2 transitions, got {marks}")
        transitions.append((y, marks[0], marks[1]))

    d0, d1 = dt.date(Y0, 1, 1), dt.date(Y1, 12, 31)
    ndays = (d1 - d0).days + 1
    bits = bytearray((ndays + 7) // 8)
    for i in range(ndays):
        d = d0 + dt.timedelta(days=i)
        if is_dst(dt.datetime(d.year, d.month, d.day, 12, tzinfo=dt.timezone.utc)):
            bits[i >> 3] |= 1 << (i & 7)

    hours: list[tuple[int, int, str]] = []  # (year, which, 24-char string of 'S'/'D')
    for y, start, end in transitions:
        for which, inst in ((0, start), (1, end)):
            day = dt.datetime.fromtimestamp(inst, tz=dt.timezone.utc).date()
            s = "".join("D" if is_dst(dt.datetime(day.year, day.month, day.day, h, tzinfo=dt.timezone.utc)) else "S" for h in range(24))
            hours.append((y, which, s))

    out.write("// GENERATED by docs/verification/core/gen_dst.py from the IANA tz database via Python\n")
    out.write(f"// zoneinfo ({zoneinfo.ZoneInfo('America/New_York').key}, tzdata as installed). DO NOT EDIT BY HAND.\n")
    out.write("#pragma once\n\n#include <cstdint>\n\nnamespace nycsim_test_dst {\n\n")
    out.write(f"inline constexpr int32_t kFirstYear = {Y0};\ninline constexpr int32_t kLastYear = {Y1};\n")
    out.write(f"inline constexpr int32_t kDayCount = {ndays};\n")
    out.write("inline constexpr int64_t kFirstDayUnix = %d;  // 2007-01-01T00:00:00Z\n\n" % int(dt.datetime(Y0, 1, 1, tzinfo=dt.timezone.utc).timestamp()))
    out.write("// {year, dst_start_unix, dst_end_unix}\n")
    out.write("inline constexpr int64_t kDstTransitions[][3] = {\n")
    for y, a, b in transitions:
        out.write(f"    {{{y}, {a}, {b}}},\n")
    out.write("};\n\n")
    out.write("// One bit per UTC day from 2007-01-01: set when 12:00 UTC of that day is EDT.\n")
    out.write("inline constexpr uint8_t kIsDstBits[] = {\n")
    for i in range(0, len(bits), 16):
        out.write("    " + " ".join(f"0x{b:02x}," for b in bits[i:i + 16]) + "\n")
    out.write("};\n\n")
    out.write("// Offset per UTC hour on both transition days: 'S' = EST, 'D' = EDT.\n")
    out.write("struct TransitionDay { int32_t year; int32_t which; const char* hours; };\n")
    out.write("inline constexpr TransitionDay kTransitionHours[] = {\n")
    for y, w, s in hours:
        out.write(f'    {{{y}, {w}, "{s}"}},\n')
    out.write("};\n\n}  // namespace nycsim_test_dst\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
