// GENERATED by docs/verification/core/gen_usno_cases.py.
// Ground truth: U.S. Naval Observatory Astronomical Applications API v4
// (https://aa.usno.navy.mil/api/rstt/oneday), a U.S. Government work in the public
// domain. Raw responses archived in docs/verification/core/usno_oneday.json.
// Site: 40.7831 N, 73.9712 W (Central Park / KNYC). Times are local minutes after
// midnight on the given EST/EDT offset (tz_hours). DO NOT EDIT BY HAND.
#pragma once

#include <cstdint>

namespace nycsim_test_usno {

struct UsnoDay {
  int32_t y, mo, d;
  int32_t tz_hours;
  int32_t rise_min, transit_min, set_min;
  int32_t civil_begin_min, civil_end_min;
  int32_t moon_fracillum_pct;
};
inline constexpr UsnoDay kUsnoDays[] = {
    {2024, 2, 29, -5, 391, 728, 1067, 363, 1094, 78},
    {2026, 1, 1, -5, 440, 720, 999, 409, 1030, 96},
    {2026, 2, 14, -5, 411, 730, 1049, 383, 1078, 8},
    {2026, 3, 8, -4, 439, 787, 1135, 411, 1162, 75},
    {2026, 3, 20, -4, 419, 783, 1148, 392, 1175, 3},
    {2026, 4, 15, -4, 377, 776, 1175, 349, 1204, 5},
    {2026, 5, 28, -4, 329, 773, 1218, 296, 1251, 93},
    {2026, 6, 21, -4, 325, 778, 1231, 291, 1264, 48},
    {2026, 7, 14, -4, 337, 782, 1227, 304, 1259, 0},
    {2026, 9, 22, -4, 404, 769, 1133, 376, 1160, 83},
    {2026, 11, 1, -5, 386, 699, 1012, 358, 1040, 52},
    {2026, 11, 15, -5, 403, 701, 998, 374, 1027, 33},
    {2026, 12, 21, -5, 437, 714, 991, 406, 1022, 92},
    {2027, 3, 14, -4, 429, 785, 1141, 402, 1169, 39},
    {2027, 8, 1, -4, 352, 782, 1212, 321, 1242, 1},
};
inline constexpr int kUsnoDayCount = 15;

}  // namespace nycsim_test_usno
