#!/usr/bin/env python3
"""Generate the translation units that compile <repo>/core/src/**/*.cpp inside the NYCSimCore UE module.

UnrealBuildTool compiles only source files that live under a module directory. The engine-agnostic library
lives in <repo>/core, so this script writes wrapper .cpp files into
``unreal/NYCSim/Source/NYCSimCore/Private/CoreUnity/`` (mode ``split``, default: one wrapper per core source,
identical translation-unit boundaries to the CMake build) or a single ``Private/CoreUnity.cpp`` that includes
every core source (mode ``unity``). The two modes are mutually exclusive; switching modes removes the other's
output so the module never contains both.

``--check`` compiles what was generated with the local C++ compiler (g++/clang++, ``-std=c++17 -Wall -Wextra
-Werror -fno-exceptions -fno-rtti``) exactly the way UBT will (include paths core/include + core/src, no UE
headers) and reports the result. Run it after every change to core/src.

    python3 unreal/tools/gen_core_unity.py            # split mode
    python3 unreal/tools/gen_core_unity.py --mode unity --check
"""
from __future__ import annotations

import argparse
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

log = logging.getLogger("nycsim.gen_core_unity")

REPO_ROOT = Path(os.environ.get("NYCSIM_REPO_ROOT", Path(__file__).resolve().parents[2]))
CORE_SRC = REPO_ROOT / "core" / "src"
CORE_INCLUDE = REPO_ROOT / "core" / "include"
MODULE_DIR = REPO_ROOT / "unreal" / "NYCSim" / "Source" / "NYCSimCore"
PRIVATE_DIR = MODULE_DIR / "Private"
SPLIT_DIR = PRIVATE_DIR / "CoreUnity"
UNITY_FILE = PRIVATE_DIR / "CoreUnity.cpp"
HEADER = "// GENERATED by unreal/tools/gen_core_unity.py -- do not edit; re-run the script after changing core/src.\n"

# Core sources that must never be compiled into the UE module (test mains, standalone executables).
EXCLUDE_DIRS = {"tests", "test", "traffic_standalone", "standalone", "tools", "bench", "benchmarks", "third_party"}
EXCLUDE_NAME_RE = re.compile(r"(_test|_tests|_main|_bench)\.cpp$|^main\.cpp$|^test_.*\.cpp$")


def core_sources() -> list[Path]:
    if not CORE_SRC.is_dir():
        raise FileNotFoundError(f"core sources not found: {CORE_SRC}")
    out: list[Path] = []
    for p in sorted(CORE_SRC.rglob("*.cpp")):
        rel = p.relative_to(CORE_SRC)
        if any(part in EXCLUDE_DIRS for part in rel.parts[:-1]):
            continue
        if EXCLUDE_NAME_RE.search(rel.name):
            continue
        if _has_main(p):
            log.warning("skipping %s: defines main()", rel)
            continue
        out.append(p)
    return out


def _has_main(p: Path) -> bool:
    try:
        text = p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return re.search(r"^\s*int\s+main\s*\(", text, re.M) is not None or "DOCTEST_CONFIG_IMPLEMENT" in text


def _wrapper_name(rel: Path) -> str:
    stem = "__".join(list(rel.parts[:-1]) + [rel.stem])
    return re.sub(r"[^A-Za-z0-9_]", "_", stem) + ".cpp"


def _clean_split() -> None:
    if SPLIT_DIR.is_dir():
        for f in SPLIT_DIR.glob("*.cpp"):
            f.unlink()
    else:
        SPLIT_DIR.mkdir(parents=True, exist_ok=True)


def generate(mode: str) -> list[Path]:
    sources = core_sources()
    written: list[Path] = []
    if mode == "split":
        if UNITY_FILE.exists():
            UNITY_FILE.unlink()
        _clean_split()
        for src in sources:
            rel = src.relative_to(CORE_SRC).as_posix()
            wrapper = SPLIT_DIR / _wrapper_name(Path(rel))
            wrapper.write_text(HEADER + f'// core/src/{rel}\n#include "{rel}"\n', encoding="utf-8")
            written.append(wrapper)
        keep = SPLIT_DIR / "README.txt"
        keep.write_text("Generated wrappers, one per core/src/**/*.cpp. Regenerate with unreal/tools/gen_core_unity.py.\n", encoding="utf-8")
    elif mode == "unity":
        if SPLIT_DIR.is_dir():
            shutil.rmtree(SPLIT_DIR)
        lines = [HEADER, "// Unity translation unit: every core/src/**/*.cpp of the engine-agnostic library.\n",
                 f"// {len(sources)} sources. Include paths: core/include (public), core/src (private).\n\n"]
        for src in sources:
            rel = src.relative_to(CORE_SRC).as_posix()
            lines.append(f'#include "{rel}"\n')
        UNITY_FILE.write_text("".join(lines), encoding="utf-8")
        written.append(UNITY_FILE)
    else:
        raise ValueError(mode)
    log.info("mode=%s: %d core sources -> %d translation unit(s)", mode, len(sources), len(written))
    return written


def _find_compiler() -> list[str] | None:
    for cxx in (os.environ.get("CXX"), "clang++", "g++"):
        if cxx and shutil.which(cxx):
            return [cxx]
    return None


def check(written: list[Path], jobs: int) -> bool:
    cxx = _find_compiler()
    if cxx is None:
        log.error("no C++ compiler found for --check")
        return False
    flags = ["-std=c++17", "-Wall", "-Wextra", "-Werror", "-fno-exceptions", "-fno-rtti", "-fsyntax-only",
             "-DNYCSIM_CORE_IN_UNREAL=1", f"-I{CORE_INCLUDE}", f"-I{CORE_SRC}", f"-I{MODULE_DIR / 'Public'}"]
    ok = True
    with tempfile.TemporaryDirectory() as td:
        procs: list[tuple[Path, subprocess.Popen]] = []
        pending = list(written)
        while pending or procs:
            while pending and len(procs) < jobs:
                f = pending.pop()
                procs.append((f, subprocess.Popen(cxx + flags + [str(f)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, cwd=td)))
            for f, p in list(procs):
                rc = p.poll()
                if rc is None:
                    continue
                procs.remove((f, p))
                out = p.stdout.read() if p.stdout else ""
                if rc != 0:
                    ok = False
                    log.error("FAILED %s\n%s", f.relative_to(REPO_ROOT), out.strip())
                else:
                    log.info("ok %s", f.relative_to(REPO_ROOT))
    return ok


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mode", choices=("split", "unity"), default="split")
    ap.add_argument("--check", action="store_true", help="compile the generated units with the local compiler")
    ap.add_argument("-j", "--jobs", type=int, default=max(1, min(4, os.cpu_count() or 1)))
    a = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    written = generate(a.mode)
    if a.check:
        return 0 if check(written, a.jobs) else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
