#!/usr/bin/env python3
"""Generate ``GameplayPedWardrobe.h`` -- which pedestrian body is dressed for which weather.

    python3 unreal/tools/gen_ped_wardrobe.py            # write the header
    python3 unreal/tools/gen_ped_wardrobe.py --check    # fail if it is out of date

``PedSim::assignAppearance`` computes two facts about every pedestrian it spawns and then throws one
of them away.  It sets ``kPedUmbrella`` above 0.3 mm/h of rain, which ``ANYCPedestrian`` renders as
an umbrella; and it sets ``kPedCoat`` below 12 degrees, **which nothing reads**.  Three lines above
that flag, the body itself is drawn uniformly over all 24 archetypes, so on a November morning the
crowd is dressed for July -- which is what the Bed-Stuy comparison sheet shows (J53).

The missing link is a table: *which* of the 24 bodies is dressed warmly.  That is not a judgement
the C++ can make and not a constant anyone should type twice, so it is derived here from the
generator's own published contract, ``blender_out/character/npc_variety.json``, which records each
body's resolved outfit and the wardrobe entry (with its ``slot`` and ``tags``) behind every garment.

**What is measured and what is chosen.**  Measured: which garments each body wears, and which of
those the wardrobe declares to be ``slot == "outerwear"``.  Chosen: that a hi-vis or delivery vest
is *not* warm clothing (it is worn over whatever the wearer already has on), and that a body with
no outerwear whose top is tagged ``summer`` is specifically summer dress.  New York's real clothing
distribution at a given temperature is measured nowhere in this project; this is a rule, and the
generated header says so.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
VARIETY = REPO_ROOT / "blender_out" / "character" / "npc_variety.json"
HEADER = (REPO_ROOT / "unreal" / "NYCSim" / "Source" / "NYCSimRuntime" / "Private"
          / "CoreAdapter" / "GameplayPedWardrobe.h")

#: An outerwear garment that is a work layer rather than a warm one: it is put on over whatever the
#: wearer is already in, and a Con Ed vest says nothing about the temperature.
WORK_LAYERS = ("hivis", "delivery")


def classify(doc: dict) -> dict:
    """``{"count", "warm", "summer", "detail"}`` -- the archetype indices in each class."""
    wardrobe = {g["id"]: g for g in doc.get("wardrobe", [])}
    bodies = sorted(doc.get("npcs", []), key=lambda e: int(e.get("index", 0)))
    warm: list[int] = []
    summer: list[int] = []
    detail: list[dict] = []
    for body in bodies:
        index = int(body["index"])
        resolved = body.get("resolved", {})
        outfit = [wardrobe[i] for i in resolved.get("outfit", []) if i in wardrobe]
        outer = [g for g in outfit if g.get("slot") == "outerwear"
                 and not any(t in WORK_LAYERS for t in g.get("tags", []))]
        top = next((g for g in outfit if g.get("slot") == "top"), None)
        is_summer = not outer and bool(top) and "summer" in (top.get("tags") or [])
        if outer:
            warm.append(index)
        if is_summer:
            summer.append(index)
        detail.append({"index": index, "id": body["id"],
                       "outerwear": [g["id"] for g in outer],
                       "top": (top or {}).get("id", ""),
                       "warm": bool(outer), "summer": is_summer})
    return {"count": len(bodies), "warm": warm, "summer": summer, "detail": detail}


#: Widest mask the header can hold.  A 64-bit type, and a hard limit rather than a wrap: the cast
#: grew from 24 bodies to 36 the moment the cold-weather ones were baked, and a ``uint32_t`` mask
#: silently dropped archetypes 32 to 35 -- ``0xFFF409024u`` is 36 bits wide and does not fit the type
#: it was written into (docs/DEVIATIONS.md J53).  Past 64 this file needs a different shape, and it
#: must say so rather than truncate.
MASK_BITS = 64


def _mask(indices: list[int]) -> str:
    over = [i for i in indices if i >= MASK_BITS]
    if over:
        raise SystemExit(f"archetypes {over} are past bit {MASK_BITS - 1}; the mask cannot hold them "
                         f"-- widen the header's type before baking more bodies")
    value = 0
    for i in indices:
        value |= 1 << i
    return f"0x{value:016X}uLL"


def render(info: dict) -> str:
    warm = ", ".join(str(i) for i in info["warm"]) or "none"
    summer = ", ".join(str(i) for i in info["summer"]) or "none"
    lines = [
        "#pragma once",
        "// GENERATED by unreal/tools/gen_ped_wardrobe.py from blender_out/character/npc_variety.json.",
        "// Do not edit: run the generator.  tests/test_character.py fails if the two disagree.",
        "//",
        "// Which pedestrian body is dressed for which weather.  PedSim::assignAppearance already",
        "// computes kPedCoat below 12 degrees and, before this table existed, drew the body",
        "// uniformly over all archetypes and ignored it -- so the crowd wore July clothes in",
        "// November (DEVIATIONS J53).",
        "//",
        "// Measured: which garments each body wears and which of them the wardrobe declares",
        "// slot == \"outerwear\".  Chosen: that a hi-vis or delivery vest is a work layer and not",
        "// warm clothing.  New York's real clothing distribution at a given temperature is measured",
        "// nowhere in this project, so the split below is a rule, not an observation.",
        "",
        "#include <cstdint>",
        "",
        "namespace nycsim_gameplay",
        "{",
        f"/// Bodies wearing a coat, a puffer or a jacket: archetypes {warm}.",
        f"inline constexpr uint64_t kPedWarmArchetypes = {_mask(info['warm'])};",
        f"/// Bodies in summer dress and no outer layer: archetypes {summer}.",
        f"inline constexpr uint64_t kPedSummerArchetypes = {_mask(info['summer'])};",
        f"/// Archetypes the table covers; a bit above this is not a body.",
        f"inline constexpr uint32_t kPedWardrobeArchetypes = {info['count']}u;",
        "",
        "/// One of the archetypes in `mask`, drawn from `roll` (any 32-bit value); "
        "`fallback` when the mask is empty.",
        "inline uint8_t pickArchetype(uint64_t mask, uint32_t roll, uint8_t fallback)",
        "{",
        "\tif (mask == 0uLL)",
        "\t{",
        "\t\treturn fallback;",
        "\t}",
        "\tuint32_t n = 0u;",
        "\tfor (uint64_t m = mask; m != 0uLL; m &= m - 1uLL)",
        "\t{",
        "\t\t++n;",
        "\t}",
        "\tuint32_t want = roll % n;",
        f"\tfor (uint32_t i = 0u; i < {MASK_BITS}u; ++i)",
        "\t{",
        "\t\tif ((mask & (1uLL << i)) == 0uLL)",
        "\t\t{",
        "\t\t\tcontinue;",
        "\t\t}",
        "\t\tif (want == 0u)",
        "\t\t{",
        "\t\t\treturn static_cast<uint8_t>(i);",
        "\t\t}",
        "\t\t--want;",
        "\t}",
        "\treturn fallback;",
        "}",
        "}  // namespace nycsim_gameplay",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the header is out of date")
    ap.add_argument("--json", action="store_true", help="print the classification instead")
    a = ap.parse_args(argv)
    if not VARIETY.is_file():
        print(f"{VARIETY} is missing; run blender/character/npc_generator.py", file=sys.stderr)
        return 2
    info = classify(json.loads(VARIETY.read_text()))
    if a.json:
        print(json.dumps(info, indent=1))
        return 0
    text = render(info)
    if a.check:
        current = HEADER.read_text() if HEADER.is_file() else ""
        if current != text:
            print(f"{HEADER} is out of date", file=sys.stderr)
            return 1
        return 0
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(text)
    print(f"{HEADER}: {len(info['warm'])} warm, {len(info['summer'])} summer, "
          f"{info['count']} archetypes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
