// GENERATED by docs/verification/core/gen_nycb_fixture.py. DO NOT EDIT BY HAND.
// Expected sizes and section counts of the NYCB files written by the *foundation*
// exporter pipeline/nycsim_pipeline/runtime/nycb.py.
#pragma once

#include <cstdint>

namespace nycsim_test_nycb {

struct SectionCount { const char* file; const char* section; uint32_t count; };
inline constexpr SectionCount kFixtureCounts[] = {
    {"density.nycb", "cells", 2},
    {"density.nycb", "nta_polys", 1},
    {"density.nycb", "strtab", 11},
    {"density.nycb", "vertices", 4},
    {"pois.nycb", "pois", 2},
    {"pois.nycb", "strtab", 30},
    {"roadgraph.nycb", "junction_lanes", 1},
    {"roadgraph.nycb", "lane_links", 2},
    {"roadgraph.nycb", "lanes", 2},
    {"roadgraph.nycb", "nodes", 3},
    {"roadgraph.nycb", "segments", 2},
    {"roadgraph.nycb", "strtab", 26},
    {"roadgraph.nycb", "vertices", 5},
    {"roadgraph.nycb", "yield_links", 1},
    {"signals.nycb", "controllers", 2},
    {"signals.nycb", "phases", 3},
    {"tiles.nycb", "tiles", 2},
    {"transit.nycb", "bus_routes", 1},
    {"transit.nycb", "bus_stops", 2},
    {"transit.nycb", "route_stops", 2},
    {"transit.nycb", "strtab", 35},
    {"transit.nycb", "vertices", 3},
};
inline constexpr int kFixtureCountN = 22;

struct RecordSize { const char* name; uint32_t bytes; };
inline constexpr RecordSize kRecordSizes[] = {
    {"bus_routes", 68},
    {"bus_stops", 24},
    {"cells", 32},
    {"controllers", 32},
    {"header", 24},
    {"index_entry", 40},
    {"junction_lanes", 48},
    {"lane_links", 8},
    {"lanes", 48},
    {"nodes", 24},
    {"nta_polys", 12},
    {"phases", 28},
    {"pois", 12},
    {"segments", 48},
    {"tiles", 28},
    {"vertices", 12},
};
inline constexpr int kRecordSizeN = 16;

struct StringOffset { const char* text; uint32_t offset; };
inline constexpr StringOffset kStringOffsets[] = {
    {"BROADWAY", 1},
    {"BROOKLYN BRIDGE", 10},
};
inline constexpr int kStringOffsetN = 2;

// Section counts of the real exporter output under data/processed/runtime/ at the
// time this header was generated, with the parquet row counts they must equal.
struct RealCount { const char* file; const char* section; uint32_t count; uint32_t element_size; int64_t parquet_rows; };
inline constexpr RealCount kRealCounts[] = {
    {"roadgraph.nycb", "junction_lanes", 466279, 48, 466279},
    {"roadgraph.nycb", "lane_links", 466279, 8, -1},
    {"roadgraph.nycb", "lanes", 384703, 48, 384703},
    {"roadgraph.nycb", "nodes", 79291, 24, 79291},
    {"roadgraph.nycb", "segments", 122235, 48, 122235},
    {"roadgraph.nycb", "strtab", 148757, 1, -1},
    {"roadgraph.nycb", "vertices", 3901850, 12, -1},
    {"roadgraph.nycb", "yield_links", 551241, 8, -1},
    {"signals.nycb", "controllers", 23839, 32, 23839},
    {"signals.nycb", "phases", 46981, 28, -1},
    {"transit.nycb", "bus_routes", 345, 68, -1},
    {"transit.nycb", "bus_stops", 13364, 24, -1},
    {"transit.nycb", "route_stops", 21963, 8, -1},
    {"transit.nycb", "strtab", 205860, 1, -1},
    {"transit.nycb", "vertices", 137060, 12, -1},
};
inline constexpr int kRealCountN = 15;

}  // namespace nycsim_test_nycb
