// GENERATED by docs/verification/core/gen_nycb_fixture.py. DO NOT EDIT BY HAND.
// Expected sizes and section counts of the NYCB files written by the *foundation*
// exporter pipeline/nycsim_pipeline/runtime/nycb.py.
#pragma once

#include <cstdint>

namespace nycsim_test_nycb {

struct SectionCount { const char* file; const char* section; uint32_t count; };
inline constexpr SectionCount kFixtureCounts[] = {
    {"density.nycb", "cells", 2},
    {"density.nycb", "nta_polys", 1},
    {"density.nycb", "strtab", 11},
    {"density.nycb", "vertices", 4},
    {"pois.nycb", "places", 2},
    {"pois.nycb", "pois", 2},
    {"pois.nycb", "strtab", 56},
    {"roadgraph.nycb", "junction_lanes", 1},
    {"roadgraph.nycb", "lane_links", 2},
    {"roadgraph.nycb", "lanes", 2},
    {"roadgraph.nycb", "nodes", 3},
    {"roadgraph.nycb", "segments", 2},
    {"roadgraph.nycb", "strtab", 26},
    {"roadgraph.nycb", "vertices", 5},
    {"roadgraph.nycb", "yield_links", 1},
    {"signals.nycb", "controllers", 2},
    {"signals.nycb", "phases", 3},
    {"tiles.nycb", "tiles", 2},
    {"transit.nycb", "bus_routes", 1},
    {"transit.nycb", "bus_stops", 2},
    {"transit.nycb", "route_stops", 2},
    {"transit.nycb", "strtab", 35},
    {"transit.nycb", "vertices", 3},
};
inline constexpr int kFixtureCountN = 23;

struct RecordSize { const char* name; uint32_t bytes; };
inline constexpr RecordSize kRecordSizes[] = {
    {"bus_routes", 68},
    {"bus_stops", 24},
    {"cells", 32},
    {"controllers", 32},
    {"header", 24},
    {"index_entry", 40},
    {"junction_lanes", 48},
    {"lane_links", 8},
    {"lanes", 48},
    {"nodes", 24},
    {"nta_polys", 12},
    {"phases", 28},
    {"places", 12},
    {"pois", 12},
    {"segments", 48},
    {"tiles", 28},
    {"vertices", 12},
};
inline constexpr int kRecordSizeN = 17;

struct StringOffset { const char* text; uint32_t offset; };
inline constexpr StringOffset kStringOffsets[] = {
    {"BROADWAY", 1},
    {"BROOKLYN BRIDGE", 10},
};
inline constexpr int kStringOffsetN = 2;

// The real exporter output under data/processed/runtime/ is NOT snapshotted here:
// the test reads core/tests/data/runtime/real_counts.json at run time so the roads
// stage can regenerate its data without a recompilation.

}  // namespace nycsim_test_nycb
